module.exports = {
  themeOrder: [
    'light',
    'dark',
    'cupcake',
    'tango',
    'emerald',
    'corporate',
    'synthwave',
    'retro',
    'cyberpunk',
    'valentine',
    'halloween',
    'garden',
    'forest',
    'aqua',
    'lofi',
    'pastel',
    'fantasy',
    'wireframe',
    'black',
    'luxury',
    'dracula',
    'cmyk',
    'autumn',
    'business',
    'acid',
    'lemonade',
    'night',
    'coffee',
    'winter',
    'dim',
    'nord',
    'sunset'
  ],
  variables: {
    '--rounded-box': '0.5rem ',
    '--rounded-btn': '0.375rem',
    '--rounded-tooltip': '0.25rem',
    '--animation-btn': '0.25s',
    '--animation-input': '.2s',
    '--btn-focus-scale': '0.95',
    '--border-btn': '1px',
    '--tab-border': '1px',
    '--tab-radius': '0.5rem'
  }
}
